authors:
  me:
    name: Jason Liu # TODO: update
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/4852235?v=4 # TODO:  find your github profile pic, right click & select 'copy image address' to get url
    url: https://twitter.com/intent/follow?screen_name=jxnlco # TODO: update